### ISSUE TITLE
Wizard menus have a consistent "r" option to go directly to "return to home menu"

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#106]

**Comment by dukedorje** [comment]
Does this always take you back to home?  Or just list the proposals from the current state?

**Comment by harlantwood** [comment]
@aquabu can you clarify the desired behavior?

**Comment by aquabu** [comment]
New UX Ideas. I'm going to close this one.

**Comment by aquabu** [comment]
I have a new UX interaction idea I'm closing this.
