### ISSUE TITLE
Show a cap table with ownership of community coins

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#108]
Table: User | Coins |  % of total
Optional pie chart

**Comment by hizzvizz** [comment]
Love this idea.

**Comment by harlantwood** [comment]
google has a (Deprecated) Image Charts service where we can get a chart just by constructing a URL, eg:

https://chart.googleapis.com/chart?chs=450x200&chd=t:20,30,37,44&cht=p3&chl=Harlan|Noah|Duke|Joel

Naturally, this loads the image into slack:

![](https://chart.googleapis.com/chart?chs=450x200&chd=t:20,30,37,44&cht=p3&chl=Harlan|Noah|Duke|Joel)

**Comment by harlantwood** [comment]
docs: https://developers.google.com/chart/image/docs/chart_params

**Comment by fractastical** [comment]
i've used google charts API before and it is awesome
BUT I would be super wary of using something that is deprecated.



On Wed, Oct 28, 2015 at 5:11 PM, Harlan T Wood < notifications@github.com > wrote:
docs: https://developers.google.com/ chart/image/docs/chart_params

**Comment by harlantwood** [comment]
yeah, I know, it's sad.  was so nice.

**Comment by harlantwood** [comment]
Officially: 

> Deprecation notice
> While the dynamic and interactive Google Charts are actively maintained, we officially deprecated the static Google Image Charts way back in 2012. This gives us the right to turn it off without notice, although we have no plans to do so.

We could use it anyway, and replace it with our own service if necessary, which just uses the same API and returns a PNG, eg from D3.

**Comment by fractastical** [comment]
If all we are doing is this percentage pie chart I'd say that's the best option (I've done some gnarly stuff w/ Google charts in the past that would be hard to port)

**Comment by harlantwood** [comment]
Rejecting: should have nice message if community has no owners / no coins assigned (currently https://chart.googleapis.com/chart?chs=450x200&chd=t:&cht=p3&chl=
)

**Comment by harlantwood** [comment]
fixed
