### ISSUE TITLE
colu does not work with redis on heroku -- this means private keys are stored on a transient file system!

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#116]

**Comment by harlantwood** [comment]
see also https://github.com/Colu-platform/colu-nodejs/issues/1

**Comment by dukedorje** [comment]
We cannot connect to Redis since Colu does not support passing auth info into the redis connection.  I am trying to figure out how to disable Redis altogether, since it throws an error if it can't connect.
