### ISSUE TITLE
rewrite README to reflect new wizard functionality 

### ISSUE THREAD

**Issue by fractastical** [citizencode/swarmbot#16]
Out of sync w/ current updates, possibly update after wizard is release ready.

**Comment by aquabu** [comment]
Yep made this into issue #54 and #55.

**Comment by harlantwood** [comment]
from @fractastical: first screenshoot is confusing in readme, maybe doesn’t start w/ right command?

**Comment by harlantwood** [comment]
updated cc @fractastical
