### ISSUE TITLE
Discuss / explore: Initial Interactions with Swarmbot

### ISSUE THREAD

**Issue by dukedorje** [citizencode/swarmbot#163]
from @aquabu:

The most tricky bit to sort out is the initial interactions for:
1. admin instance setup and default project for slack instance
2. users first interaction with swarmbot (which community?)
3. user changing their project

1 and 2 are *the most important* UX questions because they are the top of the funnel for using swarmbot and will influence our engagement massively. They are the difference between no one using it and people trying it and giving us more feedback / opportunity to interact.

**Comment by harlantwood** [comment]
see also https://github.com/citizencode/swarmbot/issues/167
