### ISSUE TITLE
Slack icon image doesn't show up if image > 500 KB

### ISSUE THREAD

**Issue by dukedorje** [citizencode/swarmbot#164]

**Comment by aquabu** [comment]
306kb image still reports that

Sorry, that image is too large. Try one of less than half a megabyte...

http://kpcbweb2.s3.amazonaws.com/content/734/original_continuuity-software-big-data-development-can-be-fun.jpg

**Comment by harlantwood** [comment]
thanks, should be fixed now

**Comment by aquabu** [comment]
With this image it still gives the too large message. It is under 500kb. Is the limit lower the 500kb in Slack?
