### ISSUE TITLE
"All Projects" UX Refresh

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#211]

**Comment by Jay-TechSalon** [comment]
![all projects - admin - with coins](https://cloud.githubusercontent.com/assets/7764167/11573224/04f2a4d8-99ba-11e5-925b-8252903c65e3.png)
![all projects admin first contact copy](https://cloud.githubusercontent.com/assets/7764167/11573221/04ec4f34-99ba-11e5-8fb9-74968a1916ae.png)
![all projects admin first contact](https://cloud.githubusercontent.com/assets/7764167/11573222/04ee0946-99ba-11e5-98d1-8648a3cf1e76.png)
![all projects admin no coins](https://cloud.githubusercontent.com/assets/7764167/11573223/04f0002a-99ba-11e5-8f8d-cb726355d258.png)
