### ISSUE TITLE
Spike on Ethereum Project Coins

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#217]
- [x] make project specific coins
- [ ] api calls from swarmbot to ethereum address
- [ ] dividends to project coin holders and what's the gas price

**Comment by harlantwood** [comment]
moving out of "in progress"

**Comment by fractastical** [comment]
Maybe we should sync up on this?

**Comment by fractastical** [comment]
brief update I've audited all of the DAO / asset token solutions that have been released and am working on the sort of set of dapp code that seems to be most compelling.  At the moment I've been looking first at integrating it into a web interface but might be good to schedule a time to plan how to integrate this stuff into swarmbot issuance. 

FWIW are some of the ones from the end of last month: https://github.com/fractastical/distributed-governance/tree/master/swarmtracts
