### ISSUE TITLE
Unhandled rejection Error: Key address/14cTfSmHYPzC1oAdhoJzVX7WKXS3DPQLSu

### ISSUE THREAD

**Issue by fractastical** [citizencode/swarmbot#26]
`Unhandled rejection Error: Key address/14cTfSmHYPzC1oAdhoJzVX7WKXS3DPQLSu not found.
`  at maybeWrapAsError (/Users/jdietz/tech/swarmbot/node_modules/bluebird/js/main/util.js:70:12)
`  at /Users/jdietz/tech/swarmbot/node_modules/bluebird/js/main/promise_resolver.js:41:50
`  at /Users/jdietz/tech/swarmbot/node_modules/colu/node_modules/async/lib/async.js:52:16
`  at /Users/jdietz/tech/swarmbot/node_modules/colu/node_modules/async/lib/async.js:667:30
`  at /Users/jdietz/tech/swarmbot/node_modules/colu/node_modules/async/lib/async.js:173:37
`  at Object._onImmediate `(/Users/jdietz/tech/swarmbot/node_modules/colu/node_modules/async/lib/async.js:1163:34)
`  at processImmediate [as _immediateCallback] (timers.js:345:15)

**Comment by fractastical** [comment]
Note, this error doesn't appear consistently. Sometimes it works. Sometimes it doesn't.

**Comment by dukedorje** [comment]
:-(

**Comment by harlantwood** [comment]
should be fixed ... @fractastical can you try it?

**Comment by aquabu** [comment]
@fractastial if you have a chance please try it and mark it as done if it works.
