### ISSUE TITLE
project show page should show project name at top, every time

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#265]

**Comment by harlantwood** [comment]
![screenshot 2015-12-16 13 14 01](https://cloud.githubusercontent.com/assets/38769/11854193/2204294c-a3f7-11e5-8164-f9a27ae1700e.png)

**Comment by harlantwood** [comment]
could this be a bug in slack?

**Comment by harlantwood** [comment]
datapoint: in the logs, we see the fallback text in the right order, even when these are wrong in the slack UI

**Comment by gleenn** [comment]
This was due to running an old version of Node (4.x). Upgraded and fixed!

**Comment by aquabu** [comment]
Seen again at 9:19am PT Dec 18th
