### ISSUE TITLE
set up swarmbot.slack.com for swarmbot contributors and community

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#268]

**Comment by aquabu** [comment]
Changing this to set up swarmbot.slack.com. This is where we will coordinate cross community collaboration on swarmbot and issue swarmbot project coins for contributions to swarmbot.

I'd like two bots:
- [ ] testbot
- [ ] swarmbot

@harlantwood I just invited you to swarmbot.slack.com. @dukedorje and @gleenn you both can join with your citizencode.io address. We can invite other collaborators once it's set up.

**Comment by harlantwood** [comment]
Done.  Note that there is a bug in the cap table on testnet: https://github.com/citizencode/swarmbot/issues/322
