### ISSUE TITLE
All people to "claim" bounty (i.e. mark that they have completed it)

### ISSUE THREAD

**Issue by fractastical** [citizencode/swarmbot#28]
We are calling this a "solution" most of the time.

**Comment by fractastical** [comment]
@dukedorje would be great to get your eyes on this, among other things I think we need to extend the firebase model to allow push. Looks like it also doesn't allow multiple levels of nesting by default and I'm not sure about extending that.

**Comment by aquabu** [comment]
I originally thought  that a "claim" is indicates that a community member is working on the bounty - so no one else is working on the bounty. 

The quick version of this functionality is that a community member can mark a bounty as "started". This handles multiple use cases in a lightweight manner: challenges (aka x-prize) with multiple solutions, tasks, and tasks that can be worked on by multiple people.

This flow is issue #41.

If solution issues and the "started" functionality covers this than we should close this issue.

**Comment by fractastical** [comment]
That makes three competing definitions of "claim," all of which are incompatible. I suggest we deprecate usage of that and break out:

Trust-Exchange- noun: rating, verb: rate
Submitted bounty: noun: solution (or "submission"), verb: submit
Checked out bounty: noun: in progress bounty, verb: start

I'm equally okay with using only Trust Exchange for "claim" but nervous since this namespace collision has already occurred multiple times.
