### ISSUE TITLE
UX for setting up your bitcoin address should be n00b friendly

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#303]
This is a big leap for users. The level of personal responsibility for key management is different than they may be accustomed to.

**Comment by aquabu** [comment]
- [ ] In the first message to setup your account it should tell you how to do this. 
- [ ] when selecting setup bitcoin address it should also give instructions

Is Coinbase suitable?

**Comment by harlantwood** [comment]
Also: 
- [ ] when you join the slack instance (different welcome message) it should give these instructions.

Repro: type `welcome me WxmhxTuxKfjnVQ3mLgGZaG2KPn`
