### ISSUE TITLE
faq

### ISSUE THREAD

**Issue by fractastical** [citizencode/swarmbot#31]
being worked on, results tracked by Nyan

**Comment by fractastical** [comment]
![nyan_info_draft2](https://cloud.githubusercontent.com/assets/589191/10523877/93869db2-7331-11e5-8cf6-6ff67fc5ddfa.png)

**Comment by harlantwood** [comment]
Awesome.

**Comment by dukedorje** [comment]
:-O

**Comment by fractastical** [comment]
![nyan_info_draft3_mobile](https://cloud.githubusercontent.com/assets/589191/10590874/00e4781e-7668-11e5-92e8-af0738408ef9.png)

**Comment by fractastical** [comment]
@dukedorje @harlantwood any quick comments? I'm undecided if it is worth pushing out or waiting until we have the deploy next week and then doing a v. 2

**Comment by hizzvizz** [comment]
Thanks for posted updates @fractastical. Let me know if need changes.
