### ISSUE TITLE
if colu is down, project should refuse to create... or should update with a currency on next attempt to send/etc

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#310]
Handle colu down

create project -> show error message (this doesn't access colu)
distribute coins -> show error message
fetch cap table -> maybe already handled
fetch coins across balances across all projects -> maybe already handled

**Comment by gleenn** [comment]
if project is in invalid state (colu down when creating), prevent 

create project -> show error message
distribute coins -> show error message
fetch cap table -> maybe already handled
fetch coins across balances across all projects -> maybe already handled

**Comment by gleenn** [comment]
use Knock

**Comment by gleenn** [comment]
We shouldn't send "Reward sent!" when colu fails

Error awarding 'big time rewards' to harlan. Unable to complete the transaction.
Cannot read property 'txid' of undefined

Reward sent!
