### ISSUE TITLE
Getting Started Video

### ISSUE THREAD

**Issue by hizzvizz** [citizencode/swarmbot#318]
It would be nice to have a welcome video (when the SwarmBot gets it's first PM from a user) with a run through of how to use the swarm bot, answer FAQs, and links to other videos that explain a little of how colu is being used. There could be a 4th optionin the menu that allows users to access these videos anytime they are stuck with basic questions.

**Comment by aquabu** [comment]
Yeah. I think some instructional videos would be great. I have plans to do an overview video. I have a demo script that I have been using. What do you think would be in the FAQs?
