### ISSUE TITLE
Spike on best bitcoin smart contract framework to use

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#319]
These seem like the most viable options at the moment:
- [x] [RootStock](http://rootstock.io)
- [ ] [OmniLayer](http://omnilayer.org)
- [ ] Counterparty
- [x] raw [bitcoin script](http://en.bitcoin.it/wiki/Script)
- [x] [SmartSignatures](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/blob/master/final-documents/smart-signatures.pdf)
- [ ] do we have to do a server process?
- [ ] ethereum DApp

The two things we want to do are:
- smart contract to distribute dividends to token holders
- smart contract exchange of X bitcoins for Y project coins

**Comment by dukedorje** [comment]
https://docs.google.com/spreadsheets/d/1O4XgZlfpl6KDJPw5zL7bxw6_8o8LwJZ09x6X40x5E8c/edit#gid=0

**Comment by dukedorje** [comment]
On the bitcoin blockchain, looks like Omnilayer is the only currently viable one.  The DApp ecosystem is most developed around Ethereum currently, by a large margin.

**Comment by harlantwood** [comment]
Rootstock plans to launch mid-2016: http://webonanza.com/2015/10/14/qa-with-rootstock-its-a-hybrid-merged-minedfederated-sidechain/

**Comment by dukedorje** [comment]
Fairly certain that raw bitcoin script will not do what we want. Hard to say 100% without being more of an expert in the assembly code, but I'm around 87% sure.

**Comment by harlantwood** [comment]
There are services that will split all incoming transactions to a given address:

- https://coinkite.com/faq/forward
- https://coinsplit.io

**Comment by dukedorje** [comment]
omnilayer (formerly mastercoin) and counterparty both specifically support out of the box: custom asset type, and BTC dividends based on custom asset distribution.

**Comment by harlantwood** [comment]
Closing as we pursue other directions...
