### ISSUE TITLE
Project admin can specify the number of unissued colored coins

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#320]

**Comment by aquabu** [comment]
When creating a new project the project admin should be able to enter the number of colored coins for the project.

**Comment by dukedorje** [comment]
What should the user enter to have the default number of coins?  0?

**Comment by aquabu** [comment]
How about this:

The default maximum number of project coins is 100 million. 
Type "ok" OR the maximum number of project coins that you want for this project.
