### ISSUE TITLE
Instance host can receive x% of all project coins issued on that instance

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#333]
This is the swarm.fund use case.
- [x] Heroku instance variable for HOST_PERCENTAGE and HOST_NAME
- [x] IFF this is set, it says HOST_PERCENTAGE% of project coins will be distributed to HOST_NAME in "All Projects > Your Project Coins" and "Project > Your Project Coins"

**Comment by harlantwood** [comment]
- [ ] Heroku instance variable for HOST_BTC_ADDRESS
- [ ] the percentage indicated is transferred to the HOST_BTC_ADDRESS on every transaction

@aquabu agree?  discuss?

**Comment by aquabu** [comment]
That works.

**Comment by harlantwood** [comment]
Done and deployed to edgebot, and both bots on Swarmbot slack instance, but Colu seems to be acting poorly, can't issue rewards.

**Comment by aquabu** [comment]
Is this one now working for swarm? If so you can move to done.

**Comment by harlantwood** [comment]
working on Swarm.

**Comment by harlantwood** [comment]
Except they have yet to tell us what % and friendly name they want...  will work once configured.

**Comment by vevue** [comment]
I believe we agreed on 1% with the name Swarm.   

@Ruben, can you verify?

**Comment by harlantwood** [comment]
Also need a btc address.
