### ISSUE TITLE
Wireframe design for transition from slack to logged in on web site

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#339]

**Comment by violasong** [comment]
**1. Click "Edit Project" in Slack**

<img width="640" alt="screen shot 2016-02-08 at 10 45 40 am" src="https://cloud.githubusercontent.com/assets/55994/12895421/2ecc4ef0-ce51-11e5-9f14-fd45bb5f5cd3.png">


------

**2. Link goes to a [hash url](http://security.stackexchange.com/questions/36146/login-with-a-hash-is-this-secure-enough) that automatically logs user in**

![editproject01x](https://cloud.githubusercontent.com/assets/55994/12897851/c70f3fd0-ce5e-11e5-9697-e587e17787dd.png)

------
**Other thoughts**
- Coinbase oauth could be useful
- [Slack Oauth login](https://api.slack.com/docs/oauth) looks like this:
<img width="614" alt="screen shot 2016-02-08 at 10 52 30 am" src="https://cloud.githubusercontent.com/assets/55994/12895610/2af11378-ce52-11e5-9ef3-99f226d9b3ba.png">

**Comment by violasong** [comment]
Notes from today's meeting: 
- All projects can be viewed for the first time using a hash url
- Projects can be set to public, which causes them to be listed in the CoMakery project index. (In the future, public projects can also set a pretty url or get one automatically. Private projects can require login to even view the project.)
- Both project types require Slack OAuth login to edit.

**Comment by vevue** [comment]
I re-worked the Journey map to look more like a wire frame map.  I'll continue to refine as we narrow down more details.

https://docs.google.com/drawings/d/1wWQWpYYzfDgUtooYDqmNSwOOn6p9uP1cko2Iz4fJAzU

p.s. Edit settings are open
