### ISSUE TITLE
Marketing page shows projects, search & signup

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#345]

**Comment by violasong** [comment]
Initial wireframe for logged-out homepage:

![index01x](https://cloud.githubusercontent.com/assets/55994/13121547/7f9286a2-d567-11e5-82d0-7a69a73f04ab.png)

**Comment by aquabu** [comment]
Nice there needs to be a place for partners (e.g. incubators and other crowd funding hosts) and communities that make projects (e.g. hacker spaces).

**Comment by violasong** [comment]
Updates: added "Our partners" to bottom section https://projects.invisionapp.com/d/main#/console/6341574/136215710/preview

**Comment by hizzvizz** [comment]
great work @violasong !
