### ISSUE TITLE
Upvoting strangely broken

### ISSUE THREAD

**Issue by fractastical** [citizencode/swarmbot#35]
<img width="434" alt="screenshot 2015-10-15 19 00 21" src="https://cloud.githubusercontent.com/assets/589191/10532088/df362272-736e-11e5-91ed-3baf8de85175.png">

**Comment by fractastical** [comment]
@dukedorje might be helpful for you to review this, don't really know what could have gone wrong here. Seems to be failing proposals-controller.coffee:104

**Comment by dukedorje** [comment]
Upvoting is now in the wizard flow.
