### ISSUE TITLE
Project creator can award project coins in slack

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#350]

**Comment by violasong** [comment]
Is there anything specific that needs to be changed about what's currently implemented for this? I'm assuming we were still going to go with the command line-y interaction for this.

**Comment by aquabu** [comment]
Yeah - command line. 

There should be two ways to do this:
1. a menu item dialog
2. an @user emoji command that can be used in any slack channel or a PM with the bot

**Comment by aquabu** [comment]
Deprecated.
