### ISSUE TITLE
Slack user can see all the projects for their instance

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#351]
See https://github.com/citizencode/swarmbot/issues/211

**Comment by violasong** [comment]
Assuming we're still going with command-line-style project navigation:

<img width="636" alt="screen shot 2016-02-12 at 10 25 07 am" src="https://cloud.githubusercontent.com/assets/55994/13016340/fa9b5674-d172-11e5-9d69-0364b14002d0.png">
