### ISSUE TITLE
Web user can see all the past awards for a project

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#352]
Reference https://github.com/citizencode/swarmbot/issues/212

**Comment by violasong** [comment]
* Coin icons (which could look much more refined and possibly have tiny cat heads on them) show up as gray for transactions that can still be cancelled, and gold for transactions that are final. There could be a **Cancel** button that displays on hover when an admin is viewing the history.

![pastrewards01x](https://cloud.githubusercontent.com/assets/55994/13062915/8693581c-d3f7-11e5-9d22-ce1a72c57504.png)

**Comment by aquabu** [comment]
@violasong awesome. It might need some column headers like:
Submitted, Coin Reward, Contributor, For


Also, what's our convention around using Award vs. Reward?

**Comment by violasong** [comment]
Updated mockup

![pastrewards02x](https://cloud.githubusercontent.com/assets/55994/13122972/9137ea62-d56e-11e5-8526-3f7e6f7e582b.png)

**Comment by aquabu** [comment]
Check latest design in invision.

**Comment by aquabu** [comment]
https://projects.invisionapp.com/d/main#/projects/6341574/workflow/screen/136215827

**Comment by gleenn** [comment]
To answer @aquabu, we standardized on "Reward" and "Reward Type" in the code base and if that aligns with the UI that would be nice but isn't required.

**Comment by gleenn** [comment]
Also, when does a reward become final a.k.a. un-cancelable?

**Comment by gleenn** [comment]
Also, the names look like links but we don't have an Account show page or any obvious place to link them, so I'm ignoring that

**Comment by aquabu** [comment]
@gleenn right now there's no finalization for awards that will happen later. So I guess we can just use the  finalized award icon for now. 

Also, the terminology for the front end is "Award".

**Comment by aquabu** [comment]
@gleenn yup, ignore the contributor links for now. Text with no link is fine.
