### ISSUE TITLE
Web user can see projects on application home page (different from "marketing" home page)

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#375]
User can see, perhaps in separate lists?  or color coded and mixed together?  or better:
- [ ] Featured Projects
- [ ] public project 
- [ ] projects from their "community" (slack instance) 

Also:
- [ ] Search box.

**Comment by violasong** [comment]
Iniitial projects page ideas https://projects.invisionapp.com/d/main#/console/6341574/137676916/preview
