### ISSUE TITLE
Users can see project index page

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#386]
https://projects.invisionapp.com/d/main#/console/6341574/137676916/preview

Logged in users see projects for their slack instance. But not when logged out.

Logged out users see 2 columns of projects and don't see projects for their instance.
- [ ] all public projects section with this layout:
```
* *
* *
* *
```
- [x] if logged in, show public and private projects
- [x] my projects section (with max 6 shown)
- [ ] ellipsize description if too long

**Comment by gleenn** [comment]
Also, Victoria mentions that when doing the ellipsis on the description:

"big fan of `text-overflow: ellipsis;` to avoid truncating by character count"
