### ISSUE TITLE
User can see project search page / browse all

### ISSUE THREAD

**Issue by gleenn** [citizencode/swarmbot#390]
- [ ] add browse all link to project index page
- [ ] searching from header lands with results on this page
- [ ] show search term as header "Results for 'foobar'"
- [ ] highlight projects from the logged in slack instance
- [ ] sort projects by last award activity (last time someone was rewarded)

**Comment by aquabu** [comment]
https://projects.invisionapp.com/d/main#/console/6341574/137778704/preview
