### ISSUE TITLE
Slack user sees crafted award message

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#407]
Slack message text should be:

@noah received a 100 coin small contribution award for "great design!" on the [3D Printer Quadcopter project]().
:+1: 

With description it's:
```
[slack id] received a [amount] coin [award name] award for "[description]" on the [project_name] project.
:+1: 
```

Without description it's:
```
[slack id] received a [amount] coin [award name] award on the [project_name] project.
:+1: 
```

**Comment by aquabu** [comment]
![screen shot 2016-02-25 at 5 21 30 pm](https://cloud.githubusercontent.com/assets/7595/13340330/557a0998-dbe4-11e5-90f2-0c21bd328fcc.png)

**Comment by aquabu** [comment]
Note that the slack id should function as an actual slack id in slack. It should ping the user that they have been mentioned. It looks like the current version treats ids like @noahthorp as just text.

**Comment by harlantwood** [comment]
@aquabu I recommend we replace `the [project_name] project` with just `[project_name]` -- I think it will work for a much wider variety of names.

**Comment by aquabu** [comment]
@harlantwood ok
