### ISSUE TITLE
Award creator should be able to select recipient from all slack users in the project's slack instance

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#417]

**Comment by aquabu** [comment]
![screen shot 2016-02-29 at 2 37 22 pm](https://cloud.githubusercontent.com/assets/7595/13411474/0b498e32-def2-11e5-93e5-e1beefd1ee00.png)

**Comment by aquabu** [comment]
To create an award the user must currently be logged in to slack for that project.
