### ISSUE TITLE
Progenitor can award bounties

### ISSUE THREAD

**Issue by aquabu** [citizencode/swarmbot#53]
Was working, now it's not. Should work for old wizardless code and new wizarded branches once it is merged.

**Comment by fractastical** [comment]
Can you comment on this additionally @harlan? One of the colu issues that
prevented asset sending appeared inconsistently

On Tue, Oct 27, 2015 at 10:32 AM, Harlan T Wood < notifications@github.com > wrote:
Closed #53 .

**Comment by harlantwood** [comment]
Duplicate issue, feature is still in progress.

**Comment by harlantwood** [comment]
See #95

**Comment by harlan** [comment]
wrong harlan!
