### ISSUE TITLE
Correctly handle certain characters in firebase keys

### ISSUE THREAD

**Issue by dukedorje** [citizencode/swarmbot#88]
Firebase doesn't allow ".", "#", "$", "[", or "]"
Scrub them in some way out of the id in our models.

**Comment by fractastical** [comment]
I implemented this in a regex at some point, but don't think I got all the
way to adding it to the model

**Comment by dukedorje** [comment]
"Sorry.  These characters are not currently allowed."   [then same prompt to re-enter the text]     
OR
We fix it so the key/id is human-readable but not the same as the user-entered string

**Comment by harlantwood** [comment]
@aquabu @fractastical to test this, create communities, proposals, and solutions containing characters: `. # $ [ ]`
