### ISSUE TITLE
Move awarding bounty into wizard flow

### ISSUE THREAD

**Issue by dukedorje** [citizencode/swarmbot#95]

**Comment by aquabu** [comment]
* Progenitors see solutions on proposal page
* Can select a number to "Award Bounty" for the solution
* Can free enter a bounty amount to reward

**Comment by harlantwood** [comment]
https://docs.google.com/spreadsheets/d/1STKLjP9PIvBt7NwyN9s4wJF-2xPpvUEIxzWKU3u1LRc/edit#gid=0

**Comment by harlantwood** [comment]
*Solution: Try stuff*
http://swarmbot.io

1: Vote Up
2: Send Reward 
x: Exit

To take an action, simply enter the number or letter at the beginning of the line.

> 2

Enter reward amount to send to Duke for the solution "Try Stuff":

> 1000

Sending reward!

_PM to solution creator:_

You have received a reward of amount 1000 for your solution LINK
